[PB-1645] fix: Check if directories (root and temp) exists on start fuseapp
internxt/drive-desktop pull request #452
Opened 2024-02-07 09:57 UTC by ldandradesw

https://inxt.atlassian.net/browse/PB-1645

2024-02-07 13:19 UTC, JoanVicens approved these changes
I've tested the app and the app still crashes on logout. But I think that this error is not related to the folder not existing but a listener in the ipc render that cannot be removed.

2024-02-07 13:21 UTC, JoanVicens requested changes
Without the log that the folder exists its good to go

2024-02-08 10:58 UTC, ldandradesw commented on src/apps/shared/fs/ensure-folder-exists.ts
> +    Logger.info(`Folder <${folder}> already exists`);
Ready the change

2024-02-08 11:00 UTC, ldandradesw commented
> I've tested the app and the app still crashes on logout. But I think that this error is not related to the folder not existing but a listener in the ipc render that cannot be removed.

![image](https://github.com/internxt/drive-desktop/assets/97113009/c5d83e4d-180e-414d-a470-926737f26ea7)

I don't see the error when I test the logout process

2024-02-14 11:34 UTC, JoanVicens approved these changes

2024-02-29 10:26 UTC, merged